[package]
name = "_rust-for-typescript-devs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
